[package]
name = "d2_calculation_api"
edition = "2021"
version = "0.1.0"
rust-version = "1.65"


[dependencies]
serde = { version = "^1.0", features = ["derive"] }


[lib]
crate-type = ["cdylib", "rlib"]

#wasm
[target.'cfg(target_arch = "wasm32")'.dependencies]
serde-wasm-bindgen = "^0.4"
console_error_panic_hook = "0.1.7"
wasm-bindgen-futures = "^0.4"
wasm-bindgen = "^0.2"
js-sys = "^0.3"
tsify = "0.4.3"

#python
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pyo3 = { version = "^0.17", features = ["extension-module"] }

[profile.release]
opt-level = 2 # fast and small wasm

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2
