[package]
name = "D2WEBAPPRUST"
edition = "2021"
version = "0.1.0"
rust-version = "1.65"


[dependencies]
serde = { version = "^1.0", features = ["derive"] }
serde-wasm-bindgen = "^0.4"
console_error_panic_hook = "0.1.6"
wasm-bindgen-futures = "^0.4"
wasm-bindgen = "^0.2"
js-sys = "^0.3"
tsify = "0.4.3"
#js-intern = "^0.3"

[lib]
crate-type = ["cdylib", "rlib"]


[profile.release]
opt-level = 2 # fast and small wasm

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2
